In [1]:
# %load quick_imports.txt
# %load quick_imports.txt
import random
import sys

import numpy as np
import matplotlib.pyplot as plt

# Bokeh imports
from bokeh.io import output_notebook, show, save
from bokeh.plotting import figure, output_file, ColumnDataSource, reset_output
from bokeh.models import HoverTool
output_notebook()

from ipywidgets.widgets import Text

#scipy constants
from scipy.constants import Boltzmann as kB
from scipy.constants import Avogadro as NA
from scipy.constants import Planck as h
from scipy.constants import speed_of_light as c0
from scipy.constants import R

sys.path.append('../CNT-SIM/')
from CNTSimFile import CNTSimFile
from mc_sim import exciton_sim_4_level, exciton_sim_4_lvl_full_exchange

Loading BokehJS ...

In [2]:
k_er_per_s = 1.5e10  # constant for radiativ decay from S11
k_br_per_s = 2.5e09  # constant for radiativ decay from S11*
k_enr_per_s = 5e09  # constant of non-radiativ decay from S11
k_bnr_per_s = 5e09  # constant for non-radiativ decay from S11*

k_de_per_s = 1e11  # constant for going from dark to S11 state
k_ed_per_s = 1e11  # constant for going from S11 to dark statestate

# termal detrapping 10.1021/acs.jpclett.8b03732
#k_bd_per_s = 0.5 * (1e12 / 385 + 1e12 / 1132) + 0.1e12 * np.exp(-1.6182e-11 /
#                                                                (kB * 300))

k_bd_per_s = 0

In [3]:
KIN_CONST = np.array([k_br_per_s, k_er_per_s, k_bnr_per_s, k_enr_per_s, k_bd_per_s, k_ed_per_s, k_de_per_s])

In [4]:
np.arange(10, 811, 400)

array([ 10, 410, 810])

In [5]:
SimTest_1 = CNTSimFile('../sim_output/SimTest_1.h5', KIN_CONST)

Existing file loaded successfully.


../CNT-SIM/CNTSimFile.py:29: UserWarning: File already exists, kinetic constants ingored.
  warn("File already exists, kinetic constants ingored.")


In [6]:
SimTest_1.length_dependance(5000, exciton_sim_4_level, np.arange(10, 811, 400), 20 , {'t_step': 1, 'r_exc_nm': 2})

2020-04-16 10:43:11.490752


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 10:43:38.960501
elapsed time: 00:00:27


In [6]:
SimTest_1.QY

array([[0.    , 0.    ],
       [0.    , 0.0114],
       [0.0008, 0.022 ]], dtype=float32)

In [8]:
SimTest_1.save()

No backwards pathways

In [7]:
SimTest_2 = CNTSimFile('../sim_output/SimTest_2.h5', KIN_CONST)

Existing file loaded successfully.


In [10]:
SimTest_2.length_dependance(5000, exciton_sim_4_level, np.arange(10, 811, 400), 20 , {'t_step': 1, 'r_exc_nm': 2})

2020-04-16 10:43:40.272906


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 10:44:07.531198
elapsed time: 00:00:27


In [10]:
SimTest_2.QY*100

array([[0.  , 0.  ],
       [0.04, 1.26],
       [0.12, 2.02]], dtype=float32)

In [13]:
SimTest_2.save()

In [11]:
SimTest_3 = CNTSimFile('../sim_output/SimTest_3.h5', KIN_CONST)

Existing file loaded successfully.


In [15]:
SimTest_3.length_dependance(5000, exciton_sim_4_level, np.arange(10, 811, 400), 20 , {'t_step': 1, 'r_exc_nm': 2})

2020-04-16 10:44:09.851103


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 10:44:40.990225
elapsed time: 00:00:31


In [16]:
SimTest_3.p_fate

array([[0.0000e+00, 0.0000e+00, 0.0000e+00, 5.0000e+03, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
       [8.0000e+00, 0.0000e+00, 1.1700e+02, 4.8750e+03, 0.0000e+00,
        1.4500e+02, 3.0201e+04, 1.9203e+04, 0.0000e+00, 1.1800e+02],
       [5.0000e+00, 0.0000e+00, 2.7300e+02, 4.7220e+03, 0.0000e+00,
        2.8700e+02, 5.8255e+04, 3.9777e+04, 0.0000e+00, 2.5200e+02]])

In [17]:
SimTest_3.QY

array([[0.    , 0.    ],
       [0.0016, 0.    ],
       [0.001 , 0.    ]])

In [18]:
SimTest_3.save()

In [19]:
k_er_per_s = 1e12  # constant for radiativ decay from S11
k_br_per_s = 1e12  # constant for radiativ decay from S11*
k_enr_per_s = 1e09  # constant of non-radiativ decay from S11
k_bnr_per_s = 1e09  # constant for non-radiativ decay from S11*

k_de_per_s = 1e09  # constant for going from dark to S11 state
k_ed_per_s = 2.5e12  # constant for going from S11 to dark statestate

# termal detrapping 10.1021/acs.jpclett.8b03732
#k_bd_per_s = 0.5 * (1e12 / 385 + 1e12 / 1132) + 0.1e12 * np.exp(-1.6182e-11 /
#                                                                (kB * 300))

k_bd_per_s = 0
KIN_CONST = np.array([k_br_per_s, k_er_per_s, k_bnr_per_s, k_enr_per_s, k_bd_per_s, k_ed_per_s, k_de_per_s])

In [12]:
SimTest_4 = CNTSimFile('../sim_output/SimTest_4.h5', KIN_CONST)

Existing file loaded successfully.


In [21]:
SimTest_4.length_dependance(5000, exciton_sim_4_level, np.arange(10, 811, 400), 20 , {'t_step': 0.1, 'r_exc_nm': 2})

2020-04-16 10:44:42.177832


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 10:45:27.924091
elapsed time: 00:00:45


In [14]:
SimTest_4.QY*100

array([[0.        , 0.        ],
       [0.65999997, 0.06      ],
       [1.54      , 0.04      ]], dtype=float32)

In [23]:
SimTest_4.save()

In [50]:
k_er_per_s = 5e10  # constant for radiativ decay from S11
k_br_per_s = 1.5e09  # constant for radiativ decay from S11*
k_enr_per_s = 5e09  # constant of non-radiativ decay from S11
k_bnr_per_s = 5e09  # constant for non-radiativ decay from S11*

k_de_per_s = 1e10  # constant for going from dark to S11 state
k_ed_per_s = 1e10  # constant for going from S11 to dark statestate

# termal detrapping 10.1021/acs.jpclett.8b03732
k_bd_per_s = 0.5 * (1e12 / 385 + 1e12 / 1132) + 0.1e12 * np.exp(-1.6182e-11 /
                                                                (kB * 300))

k_de_per_s = k_bd_per_s

KIN_CONST = [k_br_per_s, k_er_per_s, k_bnr_per_s, k_enr_per_s, k_bd_per_s, k_ed_per_s, k_de_per_s,]

In [17]:
SimTest_5 = CNTSimFile('../sim_output/SimTest_5.h5', KIN_CONST)

Existing file loaded successfully.


In [52]:
SimTest_5.length_dependance(5000, exciton_sim_4_lvl_full_exchange, np.arange(10, 811, 400), 20 , {'t_step': 1, 'r_exc_nm': 2})

2020-04-16 13:37:50.997041


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 13:41:20.996287
elapsed time: 00:03:29


In [19]:
SimTest_5.QY*100

array([[0.       , 0.       ],
       [2.5800002, 0.08     ],
       [2.54     , 0.08     ]], dtype=float32)

In [54]:
SimTest_5.save()

In [56]:
k_er_per_s = 1e12  # constant for radiativ decay from S11
k_br_per_s = 1e12  # constant for radiativ decay from S11*
k_enr_per_s = 1e09  # constant of non-radiativ decay from S11
k_bnr_per_s = 1e09  # constant for non-radiativ decay from S11*

k_de_per_s = 1e09  # constant for going from dark to S11 state
k_ed_per_s = 2e12  # constant for going from S11 to dark statestate

# termal detrapping 10.1021/acs.jpclett.8b03732
k_bd_per_s = 0.5 * (1e12 / 385 + 1e12 / 1132) + 0.1e12 * np.exp(-1.6182e-11 /
                                                                (kB * 300))

KIN_CONST = np.array([k_br_per_s, k_er_per_s, k_bnr_per_s, k_enr_per_s, k_bd_per_s, k_ed_per_s, k_de_per_s])

In [57]:
SimTest_6 = CNTSimFile('../sim_output/SimTest_6.h5', KIN_CONST)

Existing file loaded successfully.


../CNT-SIM/CNTSimFile.py:29: UserWarning: File already exists, kinetic constants ingored.
  warn("File already exists, kinetic constants ingored.")


In [58]:
SimTest_6.length_dependance(5000, exciton_sim_4_level, np.arange(10, 811, 400), 20 , {'t_step': 0.1, 'r_exc_nm': 2})

2020-04-16 16:06:14.596325


Text(value='')

Text(value='')

Text(value='')

Text(value='')

2020-04-16 16:06:55.880265
elapsed time: 00:00:41


In [59]:
SimTest_6.QY*100

array([[0.  , 0.  ],
       [0.58, 0.06],
       [0.92, 0.1 ]])

In [55]:
SimTest_6.save()